### ISSUE TITLE
Przygotowanie skryptu to scrapowania wybranego sklepu internetowego

### ISSUE THREAD

**Issue by Buzeqq** [Buzeqq/potential-train#1]
Przygotowanie skryptu to scrapowania wybranego sklepu internetowego ->
osadzenie efektów scrapowania w folderze w repozytorium (zachować kodowanie
UTF-8)

**Comment by StanislawSm** [comment]
W paczce jest jakiś dokument na temat tego projektu i link do github, znalazłem tam taki oto kod scrapera:
https://github.com/krzysztofzajaczkowski/newdemy/tree/develop/utils/WebCrawler
